# Generated by Django 6.0.7 on 2026-07-13 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('simulation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vignettenhistorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('archiviert', models.BooleanField(default=False)),
                ('eigentuemerinnen', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vignette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zustand', models.CharField(choices=[('entwurf', 'Entwurf'), ('final', 'Final'), ('archiviert', 'Archiviert')], default='entwurf', max_length=11)),
                ('finalisiert_am', models.DateTimeField(blank=True, null=True)),
                ('fehlermuster_beschreibung', models.TextField(blank=True)),
                ('lernauftrag', models.TextField(blank=True)),
                ('arbeitsheft_beschreibung', models.TextField(blank=True, help_text='Prompt-Quelle für das Modell.')),
                ('arbeitsheft_text', models.TextField(blank=True, help_text='Was die Teilnehmer:in sieht.')),
                ('arbeitsheft_bild', models.ImageField(blank=True, help_text='Was die Teilnehmer:in sieht.', upload_to='arbeitshefte/')),
                ('schuelerin_name', models.CharField(blank=True, max_length=255)),
                ('schuelerin_geschlecht', models.CharField(blank=True, choices=[('männlich', 'Männlich'), ('weiblich', 'Weiblich')], max_length=9)),
                ('lehrperson_name', models.CharField(blank=True, max_length=255)),
                ('lehrperson_geschlecht', models.CharField(blank=True, choices=[('männlich', 'Männlich'), ('weiblich', 'Weiblich')], max_length=9)),
                ('fach', models.CharField(blank=True, max_length=255)),
                ('thema', models.CharField(blank=True, max_length=255)),
                ('klassenstufe', models.CharField(blank=True, max_length=255)),
                ('referenzdiagnose', models.TextField(blank=True)),
                ('budget_typ', models.CharField(blank=True, choices=[('schritte', 'Schritte'), ('zeit', 'Zeit')], max_length=8)),
                ('budget_wert', models.PositiveIntegerField(blank=True, null=True)),
                ('gepinnter_kern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='simulation.simulationskern')),
                ('vorgaengerin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vignetten.vignette')),
                ('historie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vignetten.vignettenhistorie')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('zustand', 'entwurf')), fields=('historie',), name='vignetten_ein_entwurf_pro_historie'), models.UniqueConstraint(condition=models.Q(('zustand', 'archiviert'), _negated=True), fields=('vorgaengerin',), name='vignetten_keine_nichtarchivierten_schwestern'), models.CheckConstraint(condition=models.Q(models.Q(('finalisiert_am__isnull', True), ('zustand', 'entwurf')), models.Q(models.Q(('zustand', 'entwurf'), _negated=True), ('finalisiert_am__isnull', False)), _connector='OR'), name='vignetten_finalisiert_am_passt_zu_zustand'), models.CheckConstraint(condition=models.Q(('zustand', 'entwurf'), models.Q(('arbeitsheft_text', ''), ('arbeitsheft_bild', ''), _negated=True), _connector='OR'), name='vignetten_arbeitsheft_text_oder_bild')],
            },
        ),
    ]
