# Generated by Django 6.0.7 on 2026-08-19 15:11

import vignetten.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vignetten', '0002_alter_vignette_arbeitsheft_bild'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vignette',
            name='arbeitsheft_beschreibung',
            field=models.TextField(blank=True, help_text='Ausführliche Beschreibung des Arbeitshefts von der zu simulierenden Schüler:in. Wird für die Simulation einbezogen. Für Teilnehmer:in nicht sichtbar.'),
        ),
        migrations.AlterField(
            model_name='vignette',
            name='arbeitsheft_bild',
            field=models.ImageField(blank=True, help_text='Abbildung des Arbeitshefts von der zu simulierenden Schüler:in. Für Teilnehmer:in sichtbar.', upload_to=vignetten.models.arbeitsheft_bild_pfad),
        ),
        migrations.AlterField(
            model_name='vignette',
            name='arbeitsheft_text',
            field=models.TextField(blank=True, help_text='Inhalt des Arbeitshefts von der zu simulierenden Schüler:in. Für Teilnehmer:in sichtbar.'),
        ),
        migrations.AlterField(
            model_name='vignette',
            name='budget_typ',
            field=models.CharField(blank=True, choices=[('schritte', 'Schritte'), ('zeit', 'Zeit')], help_text='Maß des Gesprächsbudgets, an dem das Diagnosegespräch endet und der Debrief folgt: Gesprächsschritte oder Zeit. Pro Vignette ist genau ein Maß aktiv. Für Teilnehmer:in nicht sichtbar.', max_length=8),
        ),
        migrations.AlterField(
            model_name='vignette',
            name='budget_wert',
            field=models.PositiveIntegerField(blank=True, help_text='Grenze des Gesprächsbudgets, größer als 0: Anzahl der Gesprächsschritte bzw. Sekunden — je nach gewähltem Budget-Typ. Für Teilnehmer:in nicht sichtbar.', null=True),
        ),
        migrations.AlterField(
            model_name='vignette',
            name='fach',
            field=models.CharField(blank=True, help_text='Unterrichtsfach, in dem die Vignette spielt. Wird für die Simulation einbezogen. Für Teilnehmer:in sichtbar.', max_length=255),
        ),
        migrations.AlterField(
            model_name='vignette',
            name='fehlermuster_beschreibung',
            field=models.TextField(blank=True, help_text='Ausführliche Beschreibung des Fehlermusters; bestenfalls mit Beispielen für fehlerbezogenes Verhalten. Wird für die Simulation einbezogen.'),
        ),
        migrations.AlterField(
            model_name='vignette',
            name='klassenstufe',
            field=models.CharField(blank=True, help_text='Klassenstufe der zu simulierenden Schüler:in. Wird für die Simulation einbezogen. Für Teilnehmer:in sichtbar.', max_length=255),
        ),
        migrations.AlterField(
            model_name='vignette',
            name='lehrperson_geschlecht',
            field=models.CharField(blank=True, choices=[('männlich', 'Männlich'), ('weiblich', 'Weiblich')], help_text='Geschlecht der erfahrenen Lehrperson; steuert Anrede (Frau/Herr), Pronomen und die Illustrationen der Rahmenhandlung. Wird für die Simulation nicht einbezogen. Für Teilnehmer:in sichtbar.', max_length=9),
        ),
        migrations.AlterField(
            model_name='vignette',
            name='lehrperson_name',
            field=models.CharField(blank=True, help_text='Nachname der erfahrenen Lehrperson, die durch die Hospitation führt und im Debrief nach der Diagnose fragt. Wird für die Simulation nicht einbezogen — die Lehrperson ist der simulierten Schüler:in unbekannt. Für Teilnehmer:in sichtbar.', max_length=255),
        ),
        migrations.AlterField(
            model_name='vignette',
            name='lernauftrag',
            field=models.TextField(blank=True, help_text='Beschreibung des Lern- oder Arbeitsauftrags, den die Schüler:innen im Unterricht erhalten haben. Für Teilnehmer:in sichtbar.'),
        ),
        migrations.AlterField(
            model_name='vignette',
            name='referenzdiagnose',
            field=models.TextField(blank=True, help_text='Optionale fachdidaktische Notiz der Autor:in zum Fehlermuster. Ohne jede Wirkung auf Simulation und Ablauf; sie erscheint nur in der Vignettenansicht und im Datenexport. Für Teilnehmer:in nicht sichtbar.'),
        ),
        migrations.AlterField(
            model_name='vignette',
            name='schuelerin_geschlecht',
            field=models.CharField(blank=True, choices=[('männlich', 'Männlich'), ('weiblich', 'Weiblich')], help_text='Geschlecht der zu simulierenden Schüler:in; steuert die Grammatik der Rahmenhandlung und die Illustration des Gesprächsanlasses. Wird für die Simulation einbezogen. Für Teilnehmer:in sichtbar.', max_length=9),
        ),
        migrations.AlterField(
            model_name='vignette',
            name='schuelerin_name',
            field=models.CharField(blank=True, help_text='Vorname der zu simulierenden Schüler:in. Wird für die Simulation einbezogen. Für Teilnehmer:in sichtbar.', max_length=255),
        ),
        migrations.AlterField(
            model_name='vignette',
            name='thema',
            field=models.CharField(blank=True, help_text='Unterrichtsthema, an dem das Fehlermuster auftritt. Wird für die Simulation einbezogen. Für Teilnehmer:in sichtbar.', max_length=255),
        ),
    ]
