# Generated by Django 6.0.7 on 2026-08-27 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vignetten', '0003_hilfetexte_der_editorfelder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vignette',
            name='arbeitsheft_bildbeschreibung',
            field=models.TextField(blank=True, help_text='Beschreibung dessen, was auf dem Arbeitsheft-Bild zu sehen ist. Sie ist Alt-Text für Teilnehmer:innen und wird für die Simulation einbezogen.'),
        ),
        migrations.AlterField(
            model_name='vignette',
            name='arbeitsheft_text',
            field=models.TextField(blank=True, help_text='Inhalt des Arbeitshefts von der zu simulierenden Schüler:in. Mit [bild] steht das Bild an dieser Stelle; ohne Marker steht es unter dem Text. Für Teilnehmer:in sichtbar.'),
        ),
    ]
