# Generated by Django 6.0.7 on 2026-08-27 08:18

import vignetten.models
from django.db import migrations, models


_VIGNETTENZUGEHOERIGKEIT_TRIGGER_SQL = """
    CREATE TRIGGER {name}
    {ereignis} ON erhebungen_erhebungsvignette
    FOR EACH ROW
    WHEN (
        (SELECT zustand FROM vignetten_vignette WHERE id = NEW.vignette_id)
        != 'final'
        OR NOT EXISTS (
            SELECT 1 FROM erhebungen_erhebung
            JOIN vignetten_vignette ON vignetten_vignette.id = NEW.vignette_id
            JOIN vignetten_vignettenhistorie_eigentuemerinnen
                ON vignetten_vignettenhistorie_eigentuemerinnen.vignettenhistorie_id
                = vignetten_vignette.historie_id
            WHERE erhebungen_erhebung.id = NEW.erhebung_id
              AND vignetten_vignettenhistorie_eigentuemerinnen.konto_id
                = erhebungen_erhebung.eigentuemerin_id
        )
        OR ((SELECT randomisierung FROM erhebungen_erhebung WHERE id = NEW.erhebung_id)
            = 'fest' AND NEW.position IS NULL)
        OR ((SELECT randomisierung FROM erhebungen_erhebung WHERE id = NEW.erhebung_id)
            = 'zufällig' AND NEW.position IS NOT NULL)
    )
    BEGIN
        SELECT RAISE(ABORT, 'Erhebungen brauchen eigene finale Vignetten mit passender Position.');
    END;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('erhebungen', '0011_likert_gueltig'),
        ('simulation', '0003_simulationskern_rahmenhandlung_gespraechseinleitung'),
        ('vignetten', '0004_alter_vignette_arbeitsheft_bildbeschreibung_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                "DROP TRIGGER erhebungen_gueltige_vignettenzugehoerigkeit_einfuegen;"
                "DROP TRIGGER erhebungen_gueltige_vignettenzugehoerigkeit_aendern;"
            ),
            reverse_sql=(
                _VIGNETTENZUGEHOERIGKEIT_TRIGGER_SQL.format(
                    name="erhebungen_gueltige_vignettenzugehoerigkeit_einfuegen",
                    ereignis="BEFORE INSERT",
                )
                + _VIGNETTENZUGEHOERIGKEIT_TRIGGER_SQL.format(
                    name="erhebungen_gueltige_vignettenzugehoerigkeit_aendern",
                    ereignis="BEFORE UPDATE OF erhebung_id, vignette_id, position",
                )
            ),
        ),
        migrations.AddField(
            model_name='vignette',
            name='lernauftrag_bild',
            field=models.ImageField(blank=True, help_text='Abbildung zum Lernauftrag. Für Teilnehmer:in sichtbar.', upload_to=vignetten.models.vignetten_bild_pfad),
        ),
        migrations.AddField(
            model_name='vignette',
            name='lernauftrag_bildbeschreibung',
            field=models.TextField(blank=True, help_text='Beschreibung dessen, was auf dem Lernauftrag-Bild zu sehen ist. Sie ist Alt-Text für Teilnehmer:innen und wird für die Simulation einbezogen.'),
        ),
        migrations.AlterField(
            model_name='vignette',
            name='lernauftrag_text',
            field=models.TextField(blank=True, help_text='Text des Lernauftrags. Mit [bild] steht das Bild an dieser Stelle; ohne Marker steht es unter dem Text. Für Teilnehmer:in sichtbar.'),
        ),
        migrations.AddConstraint(
            model_name='vignette',
            constraint=models.CheckConstraint(condition=models.Q(('zustand', 'entwurf'), models.Q(('lernauftrag_text', ''), ('lernauftrag_bild', ''), _negated=True), _connector='OR'), name='vignetten_lernauftrag_text_oder_bild'),
        ),
        migrations.RunSQL(
            sql=(
                _VIGNETTENZUGEHOERIGKEIT_TRIGGER_SQL.format(
                    name="erhebungen_gueltige_vignettenzugehoerigkeit_einfuegen",
                    ereignis="BEFORE INSERT",
                )
                + _VIGNETTENZUGEHOERIGKEIT_TRIGGER_SQL.format(
                    name="erhebungen_gueltige_vignettenzugehoerigkeit_aendern",
                    ereignis="BEFORE UPDATE OF erhebung_id, vignette_id, position",
                )
            ),
            reverse_sql=(
                "DROP TRIGGER erhebungen_gueltige_vignettenzugehoerigkeit_einfuegen;"
                "DROP TRIGGER erhebungen_gueltige_vignettenzugehoerigkeit_aendern;"
            ),
        ),
    ]
