# Generated by Django 6.0.7 on 2026-08-27 12:14

from django.db import migrations, models


_VIGNETTENZUGEHOERIGKEIT_TRIGGER_SQL = """
    CREATE TRIGGER {name}
    {ereignis} ON erhebungen_erhebungsvignette
    FOR EACH ROW
    WHEN (
        (SELECT zustand FROM vignetten_vignette WHERE id = NEW.vignette_id)
        != 'final'
        OR NOT EXISTS (
            SELECT 1 FROM erhebungen_erhebung
            JOIN vignetten_vignette ON vignetten_vignette.id = NEW.vignette_id
            JOIN vignetten_vignettenhistorie_eigentuemerinnen
                ON vignetten_vignettenhistorie_eigentuemerinnen.vignettenhistorie_id
                = vignetten_vignette.historie_id
            WHERE erhebungen_erhebung.id = NEW.erhebung_id
              AND vignetten_vignettenhistorie_eigentuemerinnen.konto_id
                = erhebungen_erhebung.eigentuemerin_id
        )
        OR ((SELECT randomisierung FROM erhebungen_erhebung WHERE id = NEW.erhebung_id)
            = 'fest' AND NEW.position IS NULL)
        OR ((SELECT randomisierung FROM erhebungen_erhebung WHERE id = NEW.erhebung_id)
            = 'zufällig' AND NEW.position IS NOT NULL)
    )
    BEGIN
        SELECT RAISE(ABORT, 'Erhebungen brauchen eigene finale Vignetten mit passender Position.');
    END;
"""

_TRAINING_TRIGGER_SQL = """
    CREATE TRIGGER training_nur_finale_vignetten_einbinden
    BEFORE INSERT ON training_training_vignetten
    FOR EACH ROW
    WHEN (
        SELECT zustand FROM vignetten_vignette
        WHERE id = NEW.vignette_id
    ) != 'final'
    BEGIN
        SELECT RAISE(
            ABORT,
            'Trainings können nur finale Vignetten einbinden.'
        );
    END;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('erhebungen', '0011_likert_gueltig'),
        ('training', '0001_initial'),
        ('vignetten', '0005_vignette_lernauftrag_bild_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                "DROP TRIGGER erhebungen_gueltige_vignettenzugehoerigkeit_einfuegen;"
                "DROP TRIGGER erhebungen_gueltige_vignettenzugehoerigkeit_aendern;"
                "DROP TRIGGER training_nur_finale_vignetten_einbinden;"
            ),
            reverse_sql=(
                _VIGNETTENZUGEHOERIGKEIT_TRIGGER_SQL.format(
                    name="erhebungen_gueltige_vignettenzugehoerigkeit_einfuegen",
                    ereignis="BEFORE INSERT",
                )
                + _VIGNETTENZUGEHOERIGKEIT_TRIGGER_SQL.format(
                    name="erhebungen_gueltige_vignettenzugehoerigkeit_aendern",
                    ereignis="BEFORE UPDATE OF erhebung_id, vignette_id, position",
                )
                + _TRAINING_TRIGGER_SQL
            ),
        ),
        migrations.AddField(
            model_name='vignette',
            name='arbeitsheft_simulationshinweise',
            field=models.TextField(blank=True, help_text='Hinweise zum Arbeitsheft ausschließlich für die Simulation. Für Teilnehmer:in nicht sichtbar.'),
        ),
        migrations.AddField(
            model_name='vignette',
            name='lernauftrag_simulationshinweise',
            field=models.TextField(blank=True, help_text='Hinweise zum Lernauftrag ausschließlich für die Simulation. Für Teilnehmer:in nicht sichtbar.'),
        ),
        migrations.RunSQL(
            sql=(
                _VIGNETTENZUGEHOERIGKEIT_TRIGGER_SQL.format(
                    name="erhebungen_gueltige_vignettenzugehoerigkeit_einfuegen",
                    ereignis="BEFORE INSERT",
                )
                + _VIGNETTENZUGEHOERIGKEIT_TRIGGER_SQL.format(
                    name="erhebungen_gueltige_vignettenzugehoerigkeit_aendern",
                    ereignis="BEFORE UPDATE OF erhebung_id, vignette_id, position",
                )
                + _TRAINING_TRIGGER_SQL
            ),
            reverse_sql=(
                "DROP TRIGGER erhebungen_gueltige_vignettenzugehoerigkeit_einfuegen;"
                "DROP TRIGGER erhebungen_gueltige_vignettenzugehoerigkeit_aendern;"
                "DROP TRIGGER training_nur_finale_vignetten_einbinden;"
            ),
        ),
    ]
