# Generated by Django 6.1.1 on 2026-09-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vignetten', '0007_geschlechter_nicht_leer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vignette',
            name='arbeitsheft_text',
            field=models.TextField(blank=True, help_text='Inhalt des Arbeitshefts von der zu simulierenden Schüler:in. Mit [bild] allein auf einer Zeile steht das Bild an dieser Stelle; ohne Marker steht es unter dem Text. Für Teilnehmer:in sichtbar.'),
        ),
        migrations.AlterField(
            model_name='vignette',
            name='lernauftrag_text',
            field=models.TextField(blank=True, help_text='Text des Lernauftrags. Mit [bild] allein auf einer Zeile steht das Bild an dieser Stelle; ohne Marker steht es unter dem Text. Für Teilnehmer:in sichtbar.'),
        ),
    ]
