# Generated by Django 6.0.7 on 2026-07-11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KernHistorie",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("id", 1)),
                        name="simulation_kern_historie_ist_singleton",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Simulationskern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "zustand",
                    models.CharField(
                        choices=[
                            ("entwurf", "Entwurf"),
                            ("final", "Final"),
                            ("archiviert", "Archiviert"),
                        ],
                        default="entwurf",
                        max_length=11,
                    ),
                ),
                ("finalisiert_am", models.DateTimeField(blank=True, null=True)),
                ("system_prompt_vorlage", models.TextField(blank=True, default="")),
                ("user_prompt_vorlage", models.TextField(blank=True, default="")),
                ("rahmenhandlung_einleitung", models.TextField(blank=True, default="")),
                ("rahmenhandlung_debrief", models.TextField(blank=True, default="")),
                (
                    "historie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="simulation.kernhistorie",
                    ),
                ),
                (
                    "vorgaengerin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="simulation.simulationskern",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("zustand", "entwurf")),
                        fields=("historie",),
                        name="simulation_ein_entwurf_pro_historie",
                    ),
                    models.UniqueConstraint(
                        condition=~models.Q(("zustand", "archiviert")),
                        fields=("vorgaengerin",),
                        name="simulation_keine_nichtarchivierten_schwestern",
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(
                                ("finalisiert_am__isnull", True),
                                ("zustand", "entwurf"),
                            )
                            | (~models.Q(("zustand", "entwurf"))
                               & models.Q(("finalisiert_am__isnull", False)))
                        ),
                        name="simulation_finalisiert_am_passt_zu_zustand",
                    ),
                ],
            },
        ),
    ]
