# Generated by Django 6.0.7 on 2026-07-13 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModellKonfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprachmodell', models.CharField(max_length=255)),
                ('parameter', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='AktiveModellKonfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('konfiguration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='simulation.modellkonfiguration')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('singleton', 1)), name='simulation_aktive_modell_konfiguration_ist_singleton')],
            },
        ),
    ]
