# Generated by Django 6.0.7 on 2026-09-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0003_simulationskern_rahmenhandlung_gespraechseinleitung'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='simulationskern',
            constraint=models.UniqueConstraint(condition=models.Q(('zustand', 'final')), fields=('historie',), name='simulation_eine_finale_fassung_pro_historie'),
        ),
    ]
