# Generated by Django 6.0.7 on 2026-09-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0004_simulationskern_simulation_eine_finale_fassung_pro_historie'),
    ]

    operations = [
        migrations.AddField(
            model_name='modellkonfiguration',
            name='anbieter',
            field=models.CharField(choices=[('fake', 'Fake (ohne Netz)'), ('openrouter', 'OpenRouter'), ('infomaniak', 'Infomaniak')], default='fake', max_length=10),
        ),
        migrations.AddField(
            model_name='modellkonfiguration',
            name='anbieter_basis_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='modellkonfiguration',
            name='anbieter_token',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='modellkonfiguration',
            name='parameter',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
