# Generated by Django 6.0.7 on 2026-09-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0005_modellkonfiguration_anbieterbindung'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranskriptionsKonfiguration',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('anbieter', models.CharField(choices=[('fake', 'Fake (ohne Netz)'), ('openrouter', 'OpenRouter'), ('infomaniak', 'Infomaniak')], default='fake', max_length=10)),
                ('anbieter_basis_url', models.URLField(blank=True, default='')),
                ('anbieter_token', models.CharField(blank=True, default='', max_length=255)),
                ('transkriptionsmodell', models.CharField(blank=True, default='', max_length=255)),
                ('sprache', models.CharField(default='de', max_length=5)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='simulation_transkriptions_konfiguration_ist_singleton')],
            },
        ),
    ]
