# Generated by Django 6.1.1 on 2026-10-09 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0010_modellkonfiguration_angelegt_am_bestand'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvalkatalogHistorie',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='simulation_evalkatalog_historie_ist_singleton')],
            },
        ),
        migrations.CreateModel(
            name='Evalkatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zustand', models.CharField(choices=[('entwurf', 'Entwurf'), ('final', 'Final'), ('archiviert', 'Archiviert')], default='entwurf', max_length=11)),
                ('finalisiert_am', models.DateTimeField(blank=True, null=True)),
                ('k', models.PositiveSmallIntegerField(default=3, help_text='Wie oft jeder Evalinput durchgespielt wird.', verbose_name='k')),
                ('lehrperson_vorlage', models.TextField(blank=True, default='', verbose_name='Lehrperson-Vorlage')),
                ('bewerter_vorlage', models.TextField(blank=True, default='', verbose_name='Bewerter-Vorlage')),
                ('vorgaengerin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='simulation.evalkatalog')),
                ('historie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='simulation.evalkataloghistorie')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('zustand', 'entwurf')), fields=('historie',), name='simulation_evalkatalog_ein_entwurf_pro_historie'), models.UniqueConstraint(condition=models.Q(('zustand', 'final')), fields=('historie',), name='simulation_evalkatalog_eine_finale_fassung_pro_historie'), models.UniqueConstraint(condition=models.Q(('zustand', 'archiviert'), _negated=True), fields=('vorgaengerin',), name='simulation_evalkatalog_keine_nichtarchivierten_schwestern'), models.CheckConstraint(condition=models.Q(models.Q(('finalisiert_am__isnull', True), ('zustand', 'entwurf')), models.Q(models.Q(('zustand', 'entwurf'), _negated=True), ('finalisiert_am__isnull', False)), _connector='OR'), name='simulation_evalkatalog_finalisiert_am_passt_zu_zustand')],
            },
        ),
    ]
