# Generated by Django 6.1.1 on 2026-10-09 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0011_evalkatalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='UebergreifendesKriterium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('text', models.TextField(blank=True, default='', verbose_name='Kriterium')),
                ('katalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uebergreifende_kriterien', to='simulation.evalkatalog')),
            ],
            options={
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(fields=('katalog', 'position'), name='simulation_uebergreifendes_kriterium_position_eindeutig')],
            },
        ),
    ]
