# Generated by Django 6.1.1 on 2026-10-09 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0013_eval_evalkriterium'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evalinput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('eval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='simulation.eval')),
            ],
            options={
                'ordering': ['position'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Inputschritt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('art', models.CharField(choices=[('fest', 'sagt wörtlich'), ('gelenkt', 'formuliert nach Strategie')], default='fest', max_length=10, verbose_name='Art')),
                ('text', models.TextField(blank=True, default='', verbose_name='Text')),
                ('evalinput', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schritte', to='simulation.evalinput')),
            ],
            options={
                'ordering': ['position'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='evalinput',
            constraint=models.UniqueConstraint(fields=('eval', 'position'), name='simulation_evalinput_position_eindeutig'),
        ),
        migrations.AddConstraint(
            model_name='inputschritt',
            constraint=models.UniqueConstraint(fields=('evalinput', 'position'), name='simulation_inputschritt_position_eindeutig'),
        ),
    ]
