# Generated by Django 6.0.7 on 2026-07-20 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FragebogenItemHistorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('eigentuemerinnen', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FragebogenItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zustand', models.CharField(choices=[('entwurf', 'Entwurf'), ('final', 'Final'), ('archiviert', 'Archiviert')], default='entwurf', max_length=11)),
                ('finalisiert_am', models.DateTimeField(blank=True, null=True)),
                ('typ', models.CharField(choices=[('freitext', 'Freitext'), ('likert', 'Likert-Skala')], default='freitext', max_length=9)),
                ('wortlaut', models.TextField(blank=True)),
                ('vorgaengerin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fragebogen_items.fragebogenitem')),
                ('historie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fragebogen_items.fragebogenitemhistorie')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('zustand', 'entwurf')), fields=('historie',), name='fragebogen_items_ein_entwurf_pro_historie'), models.UniqueConstraint(condition=models.Q(('zustand', 'archiviert'), _negated=True), fields=('vorgaengerin',), name='fragebogen_items_keine_nichtarchivierten_schwestern'), models.CheckConstraint(condition=models.Q(models.Q(('finalisiert_am__isnull', True), ('zustand', 'entwurf')), models.Q(models.Q(('zustand', 'entwurf'), _negated=True), ('finalisiert_am__isnull', False)), _connector='OR'), name='fragebogen_items_finalisiert_am_passt_zu_zustand')],
            },
        ),
    ]
