"""Erstellt die Grundmodelle für Erhebungen und Stichproben."""

# Generated by Django 6.0.7 on 2026-07-15 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Initiale Datenbankmigration der Erhebungen-App."""

    initial: bool = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Erhebung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("entwurf", "Entwurf"),
                            ("final", "Final"),
                            ("archiviert", "Archiviert"),
                        ],
                        default="entwurf",
                        max_length=10,
                    ),
                ),
                ("instruktionstext", models.TextField(blank=True)),
                ("einwilligungstext", models.TextField(blank=True)),
                ("abschlusstext", models.TextField(blank=True)),
                (
                    "randomisierung",
                    models.CharField(
                        choices=[
                            ("fest", "Feste Reihenfolge"),
                            ("zufällig", "Zufällige Reihenfolge"),
                        ],
                        default="fest",
                        max_length=9,
                    ),
                ),
                (
                    "eigentuemerin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Stichprobe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("beginn", models.DateTimeField()),
                ("ende", models.DateTimeField()),
                ("archiviert", models.BooleanField(default=False)),
                (
                    "erhebung",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="erhebungen.erhebung",
                    ),
                ),
            ],
        ),
    ]
