# Generated by Django 6.0.7 on 2026-07-15 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "erhebungen",
            "0003_merge_0002_erhebung_modell_konfiguration_0002_erhebungsbindung_teilnahme_link",
        ),
        ("sitzungen", "0005_teilnahme_audioverarbeitung_eingewilligt"),
        ("vignetten", "0002_alter_vignette_arbeitsheft_bild"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vignettenposition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                (
                    "erhebungsbindung",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vignettenpositionen",
                        to="erhebungen.erhebungsbindung",
                    ),
                ),
                (
                    "sitzung",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sitzungen.sitzung",
                    ),
                ),
                (
                    "vignette",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="vignetten.vignette",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("erhebungsbindung", "position"),
                        name="erhebungen_position_ist_je_teilnahme_eindeutig",
                    )
                ],
            },
        ),
    ]
