# Generated by Django 6.0.7 on 2026-07-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erhebungen', '0007_merge_issue_83_issue_84'),
    ]

    operations = [
        migrations.AddField(
            model_name='erhebungsbindung',
            name='erstellt_am',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
