# Generated by Django 6.0.7 on 2026-07-23 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erhebungen', '0009_erhebungsitem'),
        ('sitzungen', '0007_gespraechsschritt_erstellt_am'),
    ]

    operations = [
        migrations.AddField(
            model_name='erhebungsbindung',
            name='abgeschlossen_am',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ItemAntwort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freitext', models.TextField(blank=True, null=True)),
                ('likert_stufe', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('vorgelegt_am', models.DateTimeField(auto_now_add=True)),
                ('erhebungsbindung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemantworten', to='erhebungen.erhebungsbindung')),
                ('erhebungsitem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='antworten', to='erhebungen.erhebungsitem')),
                ('sitzung', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitzungen.sitzung')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('sitzung__isnull', False)), fields=('erhebungsbindung', 'erhebungsitem', 'sitzung'), name='erhebungen_antwort_je_sitzung_eindeutig'), models.UniqueConstraint(condition=models.Q(('sitzung__isnull', True)), fields=('erhebungsbindung', 'erhebungsitem'), name='erhebungen_antwort_am_ende_eindeutig'), models.CheckConstraint(condition=models.Q(('freitext__isnull', True), ('likert_stufe__isnull', True), _connector='OR'), name='erhebungen_antwort_hoechstens_ein_wert')],
            },
        ),
    ]
