# Generated by Django 6.0.7 on 2026-07-23 07:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erhebungen', '0010_itemantworten'),
        ('sitzungen', '0007_gespraechsschritt_erstellt_am'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemantwort',
            name='likert_stufe',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AddConstraint(
            model_name='itemantwort',
            constraint=models.CheckConstraint(condition=models.Q(('likert_stufe__isnull', True), models.Q(('likert_stufe__gte', 1), ('likert_stufe__lte', 6)), _connector='OR'), name='erhebungen_antwort_likert_gueltig'),
        ),
    ]
