# Generated by Django 6.0.7 on 2026-09-21 15:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erhebungen', '0014_itemblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemantwort',
            name='likert_stufe',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
        ),
    ]
