# Generated by Django 6.0.7 on 2026-09-22 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erhebungen', '0015_alter_itemantwort_likert_stufe'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vignettenposition',
            name='erhebungen_position_ist_je_teilnahme_eindeutig',
        ),
        migrations.DeleteModel(
            name='Vignettenposition',
        ),
    ]
