# Generated by Django 6.0.7 on 2026-09-21 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitzungen', '0007_gespraechsschritt_erstellt_am'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gespraechsschritt',
            name='native_reasoning_spur',
        ),
    ]
