# Generated by Django 6.0.7 on 2026-09-22 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitzungen', '0010_diagnose_eingabemodus'),
        ('vignetten', '0007_geschlechter_nicht_leer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vignettenposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('sitzung', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sitzungen.sitzung')),
                ('teilnahme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vignettenpositionen', to='sitzungen.teilnahme')),
                ('vignette', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vignetten.vignette')),
            ],
            options={
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(fields=('teilnahme', 'position'), name='sitzungen_position_ist_je_teilnahme_eindeutig')],
            },
        ),
    ]
