# Generated by Django 6.1.1 on 2026-09-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitzungen', '0012_sitzung_budgetstand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teilnahme',
            name='einwilligung_erteilt',
        ),
        migrations.AddField(
            model_name='teilnahme',
            name='speicherung_eingewilligt',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='teilnahme',
            name='sprachmodell_eingewilligt',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
