# Generated by Django 6.0.7 on 2026-07-14 10:04

"""Erstellt die Modelle und die Vignetten-Integritätsprüfung für Trainings."""

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Initiale Datenbankmigration der Training-App."""

    initial = True

    dependencies = [
        ("sitzungen", "0004_fehlversuch_bewahren"),
        ("vignetten", "0002_alter_vignette_arbeitsheft_bild"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Training",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "zustand",
                    models.CharField(
                        choices=[
                            ("entwurf", "Entwurf"),
                            ("veröffentlicht", "Veröffentlicht"),
                        ],
                        default="entwurf",
                        max_length=14,
                    ),
                ),
                (
                    "eigentuemerin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("vignetten", models.ManyToManyField(to="vignetten.vignette")),
            ],
        ),
        migrations.CreateModel(
            name="Trainingsbindung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "konto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "teilnahme",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sitzungen.teilnahme",
                    ),
                ),
                (
                    "training",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="training.training",
                    ),
                ),
            ],
        ),
        migrations.RunSQL(
            sql="""
                CREATE TRIGGER training_nur_finale_vignetten_einbinden
                BEFORE INSERT ON training_training_vignetten
                FOR EACH ROW
                WHEN (
                    SELECT zustand FROM vignetten_vignette
                    WHERE id = NEW.vignette_id
                ) != 'final'
                BEGIN
                    SELECT RAISE(
                        ABORT,
                        'Trainings können nur finale Vignetten einbinden.'
                    );
                END;
            """,
            reverse_sql="DROP TRIGGER training_nur_finale_vignetten_einbinden;",
        ),
    ]
