# Generated by Django 6.0.7 on 2026-07-14 11:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sitzungen", "0004_fehlversuch_bewahren"),
        ("training", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="trainingsbindung",
            constraint=models.UniqueConstraint(
                fields=("training", "konto"),
                name="training_bindung_ist_je_konto_eindeutig",
            ),
        ),
    ]
