# Generated by Django 6.0.7 on 2026-09-22 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitzungen', '0012_sitzung_budgetstand'),
        ('training', '0003_training_eigentuemerinnen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Abschrift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erhebungsname', models.CharField(max_length=255)),
                ('importiert_am', models.DateTimeField(auto_now_add=True)),
                ('konto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('teilnahme', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sitzungen.teilnahme')),
            ],
        ),
    ]
