# Generated by Django 6.1.1 on 2026-10-09 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_trainings_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='abschrift',
            name='freigegeben_fuer',
            field=models.ManyToManyField(blank=True, related_name='freigegebene_abschriften', to='training.training'),
        ),
    ]
